const STRING_PANEL = {
  TITLE_REGISTRATION: "Formulaire de connexion",
  TEXT_EMAIL: "Adresse email",
  TEXT_EMAIL_VALID: "Adresse email valide",
  TEXT_PASSWORD: "Mot de passe",
  TEXT_PASSWORD_VALID: "Entrer un mot de passe",
  TEXT_REMEMBER_ME: "Se souvenir de moi",
  TEXT_FORGOT_PASSWORD: "Mot de passe oublié ?",
  TEXT_LOGIN: "Se connecter",
  MODAL_TITLE: "Mot de passe oublié",
  MODAL_BODY:
    "Entrer votre adresse email pour réinitialiser votre mot de passe",
  TEXT_PROFILE: "Profil",
  TEXT_AVIS: "Avis",
  TEXT_PORTFOLIO: "Portfolio",
  TEXT_EDIT_PROFIL: "Modifier le profil",
  TEXT_NAME: "Nom",
  TEXT_NAME_VALID: "Entrer un nom",
  TEXT_FIRSTNAME: "Prénom",
  TEXT_FIRSTNAME_VALID: "Entrer un prénom",
  TEXT_PHONE: "Téléphone",
  TEXT_PHONE_VALID: "Entrer un numéro de téléphone",
  TEXT_ADDRESS: "Adresse",
  TEXT_ADDRESS_VALID: "Entrer une adresse",
  TEXT_POSTAL_CODE: "Code postal",
  TEXT_POSTAL_CODE_VALID: "Entrer un code postal",
  TEXT_CITY: "Ville",
  TEXT_CITY_VALID: "Entrer une ville",
  TEXT_COUNTRY: "Pays",
  TEXT_COUNTRY_VALID: "Entrer un pays",
  TEXT_DESCRIPTION: "Description",
  TEXT_DESCRIPTION_VALID: "Entrer une description",
};

export default STRING_PANEL;
