export const STRING_BUTTON = {
  BUTTON_LOGIN: "Se connecter",
  BUTTON_REGISTER: "S'inscrire",
  BUTTON_FORGOT_PASSWORD: "Mot de passe oublié ?",
  BUTTON_SEND: "Envoyer",
  BUTTON_SAVE: "Enregistrer",
  BUTTON_CANCEL: "Annuler",
  BUTTON_EDIT: "Modifier",
  BUTTON_DELETE: "Supprimer",
  BUTTON_ADD: "Ajouter",
  BUTTON_ADD_AVIS: "Ajouter un avis",
  BUTTON_ADD_PORTFOLIO: "Ajouter un portfolio",
  BUTTON_ADD_SKILL: "Ajouter une compétence",
  BUTTON_ADD_LANGUAGE: "Ajouter une langue",
  BUTTON_ADD_EXPERIENCE: "Ajouter une expérience",
};
